# Generated by Django 4.2.11 on 2024-08-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cup',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=255)),
                ('c_edition', models.IntegerField()),
                ('c_teams', models.IntegerField()),
                ('c_groups', models.IntegerField()),
                ('c_g_winners', models.IntegerField()),
                ('c_games_groups', models.IntegerField()),
                ('c_games', models.IntegerField()),
                ('c_status', models.CharField(max_length=50)),
                ('c_draw_status', models.CharField(max_length=50)),
                ('c_draw_date', models.DateTimeField()),
                ('c_notes', models.TextField(blank=True, null=True)),
                ('c_active', models.BooleanField(default=False)),
            ],
        ),
    ]
