# Generated by Django 4.2.11 on 2024-08-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euro', '0002_rename_c_id_cup_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cup',
            name='c_edition',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cup',
            name='c_g_winners',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cup',
            name='c_games',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cup',
            name='c_games_groups',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cup',
            name='c_groups',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cup',
            name='c_teams',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
