# Generated by Django 4.2.11 on 2024-08-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euro', '0003_alter_cup_c_edition_alter_cup_c_g_winners_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cup',
            name='c_draw_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
