# Generated by Django 4.2.11 on 2024-08-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euro', '0004_alter_cup_c_draw_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cup',
            name='c_draw_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
