# Generated by Django 4.2.11 on 2024-08-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euro', '0005_alter_cup_c_draw_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='NTTeam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('t_nation', models.CharField(max_length=255)),
                ('t_name', models.CharField(max_length=255)),
                ('t_manager', models.CharField(max_length=255)),
                ('t_s_ranking', models.IntegerField()),
                ('t_ranking_dateupdated', models.DateTimeField(blank=True, null=True)),
                ('t_sokker_id', models.CharField(max_length=255)),
                ('t_email', models.EmailField(max_length=254)),
                ('t_created', models.DateTimeField(auto_now_add=True)),
                ('t_arena', models.CharField(max_length=255)),
            ],
        ),
    ]
