# Generated by Django 4.2.11 on 2024-08-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euro', '0006_ntteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ntteam',
            name='t_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='ntteam',
            name='t_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='ntteam',
            name='t_manager',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
