# Generated by Django 4.2.11 on 2024-08-16 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('euro', '0007_alter_ntteam_t_created_alter_ntteam_t_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ntteam',
            name='t_created',
        ),
        migrations.RemoveField(
            model_name='ntteam',
            name='t_ranking_dateupdated',
        ),
    ]
