# Generated by Django 4.2.11 on 2024-08-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euro', '0008_remove_ntteam_t_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ntteam',
            name='t_s_ranking',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
