# Generated by Django 4.2.11 on 2024-08-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euro', '0012_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='group_id',
            field=models.CharField(),
        ),
    ]
