# Generated by Django 4.2.11 on 2024-08-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euro', '0013_alter_game_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='goals_away',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='goals_home',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
