# Generated by Django 4.2.11 on 2024-08-16 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('euro', '0014_alter_game_goals_away_alter_game_goals_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankGroups',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('games', models.IntegerField(blank=True, null=True)),
                ('g_id', models.IntegerField(blank=True, null=True)),
                ('wins', models.IntegerField(blank=True, null=True)),
                ('loose', models.IntegerField(blank=True, null=True)),
                ('gdif', models.IntegerField(blank=True, null=True)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('gscorered', models.IntegerField(blank=True, null=True)),
                ('grecived', models.IntegerField(blank=True, null=True)),
                ('draw', models.IntegerField(blank=True, null=True)),
                ('qualified', models.CharField(max_length=50)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='euro.cup')),
                ('t_id_h', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_rank', to='euro.ntteam')),
            ],
        ),
    ]
