# Generated by Django 4.2.11 on 2024-08-16 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('euro', '0015_rankgroups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rankgroups',
            old_name='t_id_h',
            new_name='t_id',
        ),
    ]
