# Generated by Django 4.2.11 on 2024-09-14 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euro', '0017_rename_grecived_rankgroups_grecieved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cup',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='header_images/'),
        ),
    ]
