# Generated by Django 4.2.11 on 2024-09-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euro', '0018_cup_header_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cup',
            name='forum_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
