# Generated by Django 4.2.11 on 2024-09-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euro', '0019_cup_forum_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='cup',
            name='c_flow',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
