# Generated by Django 4.2.11 on 2024-09-19 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('euro', '0020_cup_c_flow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Winners',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('cup_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='euro.cup')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_winners', to='euro.ntteam')),
            ],
        ),
        migrations.CreateModel(
            name='Medals',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('position_1', models.IntegerField(blank=True, null=True)),
                ('position_2', models.IntegerField(blank=True, null=True)),
                ('position_3', models.IntegerField(blank=True, null=True)),
                ('position_4', models.IntegerField(blank=True, null=True)),
                ('t_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_medal', to='euro.ntteam')),
            ],
        ),
    ]
