# Generated by Django 4.2.11 on 2024-09-20 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('euro', '0021_winners_medals'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankAllTime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('games', models.IntegerField(blank=True, null=True)),
                ('wins', models.IntegerField(blank=True, null=True)),
                ('loose', models.IntegerField(blank=True, null=True)),
                ('gdif', models.IntegerField(blank=True, null=True)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('gscored', models.IntegerField(blank=True, null=True)),
                ('grecieved', models.IntegerField(blank=True, null=True)),
                ('draw', models.IntegerField(blank=True, null=True)),
                ('c_flow', models.IntegerField(blank=True, default=1, null=True)),
                ('t_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_rank_all_time', to='euro.ntteam')),
            ],
        ),
    ]
