# Generated by Django 4.2.11 on 2024-10-01 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('euro', '0022_rankalltime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cupteams',
            options={'verbose_name_plural': 'Cup Teams'},
        ),
        migrations.AlterModelOptions(
            name='medals',
            options={'verbose_name_plural': 'Medals'},
        ),
        migrations.AlterModelOptions(
            name='rankgroups',
            options={'verbose_name_plural': 'Rank Groups'},
        ),
        migrations.AlterModelOptions(
            name='winners',
            options={'verbose_name_plural': 'Winners'},
        ),
    ]
