# Generated by Django 4.2.11 on 2025-03-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euro', '0023_alter_cupteams_options_alter_medals_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cup',
            name='c_start_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
