# Generated by Django 4.2.11 on 2025-05-10 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sokker_base', '0018_leaguetable'),
        ('arcades', '0017_rename_goal_cupgamestats_goals'),
        ('euro', '0025_alter_cup_c_draw_status_alter_cup_c_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EuroCupGameStats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('goals', models.IntegerField(blank=True, null=True)),
                ('assists', models.IntegerField(blank=True, null=True)),
                ('red_cards', models.IntegerField(blank=True, null=True)),
                ('yellow_cards', models.IntegerField(blank=True, null=True)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='euro.game')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='arcades.player')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sokker_base.team')),
            ],
        ),
    ]
