# Generated by Django 4.2.11 on 2025-05-10 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('euro', '0026_eurocupgamestats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eurocupgamestats',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='euro.ntteam'),
        ),
    ]
