# Generated by Django 4.2.11 on 2025-05-13 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euro', '0027_alter_eurocupgamestats_team_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='has_stats',
            field=models.BooleanField(default=False),
        ),
    ]
