# Generated by Django 4.2.11 on 2025-05-15 23:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('idcountry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footballarena.country')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('position', models.CharField(choices=[('Goalkeeper', 'Goalkeeper'), ('Defender', 'Defender'), ('Winger', 'Winger'), ('Midfielder', 'Midfielder'), ('Forward', 'Forward')], max_length=10)),
                ('height', models.IntegerField(help_text='Height in cm')),
                ('potential', models.FloatField(help_text='Potential percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('value', models.DecimalField(decimal_places=2, help_text='Value in euros', max_digits=12)),
                ('wage', models.DecimalField(decimal_places=2, help_text='Wage in euros', max_digits=10)),
                ('in_club_since', models.DateField()),
                ('condition', models.FloatField(help_text='Condition percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('form', models.FloatField(help_text='Form percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('experience', models.FloatField(help_text='Experience rating', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('overall', models.FloatField(help_text='Overall rating', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)])),
                ('stamina', models.FloatField(help_text='Stamina rating', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)])),
                ('goalkeeper', models.FloatField(help_text='Goalkeeper skill', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)])),
                ('tackling', models.FloatField(help_text='Tackling skill', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)])),
                ('heading', models.FloatField(help_text='Heading skill', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)])),
                ('winger', models.FloatField(help_text='Winger skill', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)])),
                ('playmaking', models.FloatField(help_text='Playmaking skill', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)])),
                ('passing', models.FloatField(help_text='Passing skill', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)])),
                ('attacking', models.FloatField(help_text='Attacking skill', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)])),
                ('idcountry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footballarena.country')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='footballarena.team')),
            ],
            options={
                'ordering': ['-overall'],
                'indexes': [models.Index(fields=['player_id'], name='footballare_player__790a64_idx'), models.Index(fields=['name'], name='footballare_name_a6b728_idx'), models.Index(fields=['team'], name='footballare_team_id_a2bbdf_idx')],
            },
        ),
    ]
