# Generated by Django 4.2.11 on 2024-05-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('currency_name', models.CharField(max_length=100)),
                ('currency_rate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
