# Generated by Django 4.2.11 on 2024-05-20 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sokker_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
    ]
