# Generated by Django 4.2.11 on 2024-05-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sokker_base', '0002_alter_country_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='country_id',
        ),
        migrations.AddField(
            model_name='country',
            name='code',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='country',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
