# Generated by Django 4.2.11 on 2024-05-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sokker_base', '0003_remove_country_country_id_country_code_country_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='currency_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='country',
            name='currency_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
