# Generated by Django 4.2.11 on 2024-05-23 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sokker_base', '0007_usercountry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercountry',
            options={'verbose_name_plural': 'User Countries'},
        ),
    ]
