# Generated by Django 4.2.11 on 2024-05-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sokker_base', '0008_alter_usercountry_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercountry',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
