# Generated by Django 4.2.11 on 2024-05-26 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sokker_base', '0009_usercountry_is_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsRequirementsCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gk_points', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('def_points', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mid_points', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('att_points', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sokker_base.country')),
            ],
            options={
                'verbose_name_plural': 'Point Requirements per Countries',
            },
        ),
    ]
