# Generated by Django 4.2.11 on 2024-08-08 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sokker_base', '0010_pointsrequirementscountry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.IntegerField(default=1, unique=True),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sokker_base.country', to_field='code')),
            ],
        ),
    ]
