# Generated by Django 4.2.11 on 2024-08-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sokker_base', '0011_alter_country_code_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='daily_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
