# Generated by Django 4.2.11 on 2024-08-08 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sokker_base', '0012_team_daily_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercountry',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sokker_base.country'),
        ),
    ]
