# Generated by Django 4.2.11 on 2025-01-14 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sokker_base', '0014_alter_team_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
