# Generated by Django 4.2.11 on 2025-04-24 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sokker_base', '0015_alter_team_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamTrophies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trophy_type', models.CharField(blank=True, choices=[('league', 'League'), ('national_cup', 'National Cup'), ('international', 'International'), ('champions_cup', 'Champions Cup')], max_length=250, null=True)),
                ('occurrences', models.IntegerField(blank=True, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sokker_base.country')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sokker_base.team')),
            ],
        ),
    ]
