# Generated by Django 4.2.11 on 2025-04-24 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sokker_base', '0016_teamtrophies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamtrophies',
            options={'verbose_name_plural': 'Team Trophies'},
        ),
    ]
