# Generated by Django 4.2.11 on 2025-05-02 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sokker_base', '0017_alter_teamtrophies_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.IntegerField(blank=True, null=True)),
                ('season', models.IntegerField(blank=True, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('played', models.IntegerField(blank=True, null=True)),
                ('won', models.IntegerField(blank=True, null=True)),
                ('drawn', models.IntegerField(blank=True, null=True)),
                ('lost', models.IntegerField(blank=True, null=True)),
                ('scored', models.IntegerField(blank=True, null=True)),
                ('conceded', models.IntegerField(blank=True, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sokker_base.country')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sokker_base.team')),
            ],
            options={
                'verbose_name_plural': 'League Table',
                'unique_together': {('league', 'country', 'team', 'season')},
            },
        ),
    ]
