# Generated by Django 4.2.11 on 2024-04-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('nr', models.IntegerField(primary_key=True, serialize=False)),
                ('id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('surname', models.CharField(blank=True, max_length=255, null=True)),
                ('countryid', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('teamid', models.IntegerField(blank=True, null=True)),
                ('youthteamid', models.IntegerField(blank=True, null=True)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('wage', models.IntegerField(blank=True, null=True)),
                ('cards', models.IntegerField(blank=True, null=True)),
                ('goals', models.IntegerField(blank=True, null=True)),
                ('assists', models.IntegerField(blank=True, null=True)),
                ('matches', models.IntegerField(blank=True, null=True)),
                ('ntcards', models.IntegerField(blank=True, null=True)),
                ('ntgoals', models.IntegerField(blank=True, null=True)),
                ('ntassists', models.IntegerField(blank=True, null=True)),
                ('ntmatches', models.IntegerField(blank=True, null=True)),
                ('injurydays', models.IntegerField(blank=True, null=True)),
                ('national', models.IntegerField(blank=True, null=True)),
                ('skillform', models.IntegerField(blank=True, null=True)),
                ('skillexperience', models.IntegerField(blank=True, null=True)),
                ('skillteamwork', models.IntegerField(blank=True, null=True)),
                ('skilldiscipline', models.IntegerField(blank=True, null=True)),
                ('transferlist', models.IntegerField(blank=True, null=True)),
                ('skillstamina', models.IntegerField(blank=True, null=True)),
                ('skillpace', models.IntegerField(blank=True, null=True)),
                ('skilltechnique', models.IntegerField(blank=True, null=True)),
                ('skillpassing', models.IntegerField(blank=True, null=True)),
                ('skillkeeper', models.IntegerField(blank=True, null=True)),
                ('skilldefending', models.IntegerField(blank=True, null=True)),
                ('skillplaymaking', models.IntegerField(blank=True, null=True)),
                ('skillscoring', models.IntegerField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=3, null=True)),
                ('date', models.CharField(blank=True, max_length=10, null=True)),
                ('time', models.CharField(blank=True, max_length=10, null=True)),
                ('deleted', models.IntegerField(default=0)),
                ('plugin', models.IntegerField(default=0)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('admin_id', models.IntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('avgrating', models.FloatField(default=0)),
                ('avgratingGK', models.FloatField(default=0)),
                ('bestRating', models.FloatField(default=0)),
                ('bestRatingGK', models.FloatField(default=0)),
                ('bestRatingLastGames', models.FloatField(default=0)),
                ('bestRatingLastGamesGK', models.FloatField(default=0)),
                ('bestRatingDate', models.DateTimeField(blank=True, null=True)),
                ('bestRatingGKDate', models.DateTimeField(blank=True, null=True)),
                ('gamescounter', models.IntegerField(default=0)),
                ('gamescounterGK', models.IntegerField(default=0)),
                ('avgratingLastGames', models.FloatField(blank=True, null=True)),
                ('avgratingLastGamesGK', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Players',
            },
        ),
    ]
