# Generated by Django 4.2.11 on 2024-04-15 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ntdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'Player'},
        ),
        migrations.RemoveField(
            model_name='player',
            name='bestRatingDate',
        ),
        migrations.RemoveField(
            model_name='player',
            name='bestRatingGKDate',
        ),
    ]
