# Generated by Django 4.2.11 on 2024-04-15 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ntdb', '0002_alter_player_options_remove_player_bestratingdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='created',
        ),
    ]
