# Generated by Django 4.2.11 on 2024-05-20 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntdb', '0003_remove_player_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='injurydays',
            field=models.IntegerField(blank=True, null=True, verbose_name='Inj.'),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Pos.'),
        ),
        migrations.AlterField(
            model_name='player',
            name='skilldefending',
            field=models.IntegerField(blank=True, null=True, verbose_name='Def'),
        ),
        migrations.AlterField(
            model_name='player',
            name='skilldiscipline',
            field=models.IntegerField(blank=True, null=True, verbose_name='TD'),
        ),
        migrations.AlterField(
            model_name='player',
            name='skillexperience',
            field=models.IntegerField(blank=True, null=True, verbose_name='Exp'),
        ),
        migrations.AlterField(
            model_name='player',
            name='skillform',
            field=models.IntegerField(blank=True, null=True, verbose_name='Form'),
        ),
        migrations.AlterField(
            model_name='player',
            name='skillkeeper',
            field=models.IntegerField(blank=True, null=True, verbose_name='Gk'),
        ),
        migrations.AlterField(
            model_name='player',
            name='skillpace',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pace'),
        ),
        migrations.AlterField(
            model_name='player',
            name='skillpassing',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pass'),
        ),
        migrations.AlterField(
            model_name='player',
            name='skillplaymaking',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pm'),
        ),
        migrations.AlterField(
            model_name='player',
            name='skillscoring',
            field=models.IntegerField(blank=True, null=True, verbose_name='Att'),
        ),
        migrations.AlterField(
            model_name='player',
            name='skillstamina',
            field=models.IntegerField(blank=True, null=True, verbose_name='St.'),
        ),
        migrations.AlterField(
            model_name='player',
            name='skillteamwork',
            field=models.IntegerField(blank=True, null=True, verbose_name='TW'),
        ),
        migrations.AlterField(
            model_name='player',
            name='skilltechnique',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tech'),
        ),
    ]
