# Generated by Django 4.2.11 on 2024-05-20 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ntdb", "0005_archiveplayer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="archiveplayer",
            name="avgrating",
        ),
        migrations.RemoveField(
            model_name="archiveplayer",
            name="avgratingGK",
        ),
        migrations.RemoveField(
            model_name="archiveplayer",
            name="avgratingLastGames",
        ),
        migrations.RemoveField(
            model_name="archiveplayer",
            name="avgratingLastGamesGK",
        ),
        migrations.RemoveField(
            model_name="archiveplayer",
            name="bestRating",
        ),
        migrations.RemoveField(
            model_name="archiveplayer",
            name="bestRatingGK",
        ),
        migrations.RemoveField(
            model_name="archiveplayer",
            name="bestRatingLastGames",
        ),
        migrations.RemoveField(
            model_name="archiveplayer",
            name="bestRatingLastGamesGK",
        ),
        migrations.RemoveField(
            model_name="archiveplayer",
            name="gamescounter",
        ),
        migrations.RemoveField(
            model_name="archiveplayer",
            name="gamescounterGK",
        ),
        migrations.RemoveField(
            model_name="archiveplayer",
            name="note",
        ),
        migrations.RemoveField(
            model_name="player",
            name="avgrating",
        ),
        migrations.RemoveField(
            model_name="player",
            name="avgratingGK",
        ),
        migrations.RemoveField(
            model_name="player",
            name="avgratingLastGames",
        ),
        migrations.RemoveField(
            model_name="player",
            name="avgratingLastGamesGK",
        ),
        migrations.RemoveField(
            model_name="player",
            name="bestRating",
        ),
        migrations.RemoveField(
            model_name="player",
            name="bestRatingGK",
        ),
        migrations.RemoveField(
            model_name="player",
            name="bestRatingLastGames",
        ),
        migrations.RemoveField(
            model_name="player",
            name="bestRatingLastGamesGK",
        ),
        migrations.RemoveField(
            model_name="player",
            name="gamescounter",
        ),
        migrations.RemoveField(
            model_name="player",
            name="gamescounterGK",
        ),
    ]
