# Generated by Django 4.2.11 on 2024-05-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntdb', '0006_remove_archiveplayer_avgrating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archiveplayer',
            name='nr',
        ),
        migrations.RemoveField(
            model_name='player',
            name='nr',
        ),
        migrations.AddField(
            model_name='archiveplayer',
            name='sokker_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='sokker_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='archiveplayer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='player',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
