# Generated by Django 4.2.11 on 2024-05-30 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntdb', '0007_remove_archiveplayer_nr_remove_player_nr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
