# Generated by Django 4.2.11 on 2024-05-30 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntdb', '0008_alter_player_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archiveplayer',
            name='admin_id',
        ),
        migrations.RemoveField(
            model_name='archiveplayer',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='archiveplayer',
            name='plugin',
        ),
        migrations.RemoveField(
            model_name='archiveplayer',
            name='time',
        ),
        migrations.RemoveField(
            model_name='player',
            name='admin_id',
        ),
        migrations.RemoveField(
            model_name='player',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='player',
            name='plugin',
        ),
        migrations.RemoveField(
            model_name='player',
            name='time',
        ),
        migrations.AddField(
            model_name='archiveplayer',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='archiveplayer',
            name='date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
