# Generated by Django 4.2.11 on 2024-06-13 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntdb', '0009_remove_archiveplayer_admin_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='daily_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
