# Generated by Django 4.2.11 on 2024-08-08 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sokker_base', '0012_team_daily_update'),
        ('ntdb', '0010_player_daily_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiveplayer',
            name='teamid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archive_player_team', to='sokker_base.team'),
        ),
        migrations.AlterField(
            model_name='archiveplayer',
            name='youthteamid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archive_youth_player_team', to='sokker_base.team'),
        ),
        migrations.AlterField(
            model_name='player',
            name='teamid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_team', to='sokker_base.team'),
        ),
        migrations.AlterField(
            model_name='player',
            name='youthteamid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='youth_player_team', to='sokker_base.team'),
        ),
    ]
