# Generated by Django 4.2.11 on 2024-09-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntdb', '0011_alter_archiveplayer_teamid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiveplayer',
            name='daily_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
