# Generated by Django 4.2.11 on 2025-01-13 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sokker_base', '0014_alter_team_country'),
        ('ntdb', '0012_archiveplayer_daily_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='NTTeamsStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_type', models.CharField(blank=True, choices=[('youth', 'From Youth Team'), ('team', 'In Club Players')], max_length=255, null=True)),
                ('ntmatches', models.IntegerField(blank=True, null=True)),
                ('ntgoals', models.IntegerField(blank=True, null=True)),
                ('ntassists', models.IntegerField(blank=True, null=True)),
                ('teamid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sokker_base.team')),
            ],
            options={
                'verbose_name': 'NT Teams Stats',
            },
        ),
    ]
