# Generated by Django 4.2.11 on 2025-01-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntdb', '0013_ntteamsstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiveplayer',
            name='retired',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='retired',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
