# Generated by Django 4.2.11 on 2025-01-17 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntdb', '0014_archiveplayer_retired_player_retired'),
    ]

    operations = [
        migrations.AddField(
            model_name='ntteamsstats',
            name='countryid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
