# Generated by Django 4.2.11 on 2025-01-17 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntdb', '0015_ntteamsstats_countryid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ntteamsstats',
            name='json_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
