# Generated by Django 4.2.11 on 2025-01-19 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntdb', '0016_ntteamsstats_json_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='ntteamsstats',
            name='ntplayers',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ntteamsstats',
            name='ntassists',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ntteamsstats',
            name='ntgoals',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ntteamsstats',
            name='ntmatches',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
