# Generated by Django 4.2.11 on 2025-01-19 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntdb', '0017_ntteamsstats_ntplayers_alter_ntteamsstats_ntassists_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ntteamsstats',
            name='json_data_youth',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
