# Generated by Django 4.2.11 on 2025-01-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntdb', '0018_ntteamsstats_json_data_youth'),
    ]

    operations = [
        migrations.AddField(
            model_name='ntteamsstats',
            name='ntseasons',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
