# fly.toml app configuration file generated for sokker on 2024-05-03T09:48:52-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sokker'
primary_region = 'yul'
console_command = '/code/manage.py shell'

[build]

[deploy]
  release_command = "sh release.sh"

[env]
  PORT = '8000'
  LOG_LEVEL = "debug"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
  kill_timeout = 3000


[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'

[mounts]
source = "sokker_data"
destination = "/data"