--
-- PostgreSQL database dump
--

-- Dumped from database version 15.0
-- Dumped by pg_dump version 17.0 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: arcades_cup; Type: TABLE; Schema: public; Owner: sokker_web
--

CREATE TABLE public.arcades_cup (
    id integer NOT NULL,
    header_image character varying(100),
    forum_link character varying(255),
    c_name character varying(255) NOT NULL,
    c_edition integer,
    c_flow integer,
    c_teams integer,
    c_groups integer,
    c_g_winners integer,
    c_games_groups integer,
    c_games integer,
    c_status character varying(50) NOT NULL,
    c_draw_status character varying(50) NOT NULL,
    c_draw_date timestamp with time zone,
    c_notes text,
    c_active boolean NOT NULL,
    category_id integer,
    is_cl boolean NOT NULL,
    c_start_date timestamp with time zone
);


ALTER TABLE public.arcades_cup OWNER TO sokker_web;

--
-- Name: arcades_cup_id_seq; Type: SEQUENCE; Schema: public; Owner: sokker_web
--

ALTER TABLE public.arcades_cup ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.arcades_cup_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: arcades_cupcategory; Type: TABLE; Schema: public; Owner: sokker_web
--

CREATE TABLE public.arcades_cupcategory (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    slug character varying(255) NOT NULL
);


ALTER TABLE public.arcades_cupcategory OWNER TO sokker_web;

--
-- Name: arcades_cupcategory_id_seq; Type: SEQUENCE; Schema: public; Owner: sokker_web
--

ALTER TABLE public.arcades_cupcategory ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.arcades_cupcategory_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: arcades_cupdraw; Type: TABLE; Schema: public; Owner: sokker_web
--

CREATE TABLE public.arcades_cupdraw (
    id integer NOT NULL,
    g_id integer NOT NULL,
    c_id_id integer NOT NULL,
    t_id_id integer NOT NULL
);


ALTER TABLE public.arcades_cupdraw OWNER TO sokker_web;

--
-- Name: arcades_cupdraw_id_seq; Type: SEQUENCE; Schema: public; Owner: sokker_web
--

ALTER TABLE public.arcades_cupdraw ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.arcades_cupdraw_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: arcades_cupteams; Type: TABLE; Schema: public; Owner: sokker_web
--

CREATE TABLE public.arcades_cupteams (
    id integer NOT NULL,
    g_id integer NOT NULL,
    c_id_id integer NOT NULL,
    t_id_id integer NOT NULL,
    pot_id integer
);


ALTER TABLE public.arcades_cupteams OWNER TO sokker_web;

--
-- Name: arcades_cupteams_id_seq; Type: SEQUENCE; Schema: public; Owner: sokker_web
--

ALTER TABLE public.arcades_cupteams ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.arcades_cupteams_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: arcades_game; Type: TABLE; Schema: public; Owner: sokker_web
--

CREATE TABLE public.arcades_game (
    id integer NOT NULL,
    g_status character varying(50) NOT NULL,
    group_id character varying NOT NULL,
    goals_home integer,
    goals_away integer,
    cup_round character varying(50) NOT NULL,
    "matchID" character varying(255) NOT NULL,
    playoff_position character varying(50),
    c_id_id integer NOT NULL,
    t_id_h_id integer,
    t_id_v_id integer
);


ALTER TABLE public.arcades_game OWNER TO sokker_web;

--
-- Name: arcades_game_id_seq; Type: SEQUENCE; Schema: public; Owner: sokker_web
--

ALTER TABLE public.arcades_game ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.arcades_game_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: arcades_medals; Type: TABLE; Schema: public; Owner: sokker_web
--

CREATE TABLE public.arcades_medals (
    id integer NOT NULL,
    position_1 integer,
    position_2 integer,
    position_3 integer,
    position_4 integer,
    t_id_id integer NOT NULL
);


ALTER TABLE public.arcades_medals OWNER TO sokker_web;

--
-- Name: arcades_medals_id_seq; Type: SEQUENCE; Schema: public; Owner: sokker_web
--

ALTER TABLE public.arcades_medals ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.arcades_medals_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: arcades_rankalltime; Type: TABLE; Schema: public; Owner: sokker_web
--

CREATE TABLE public.arcades_rankalltime (
    id integer NOT NULL,
    games integer,
    wins integer,
    loose integer,
    gdif integer,
    points integer,
    gscored integer,
    grecieved integer,
    draw integer,
    c_flow integer,
    t_id_id integer NOT NULL
);


ALTER TABLE public.arcades_rankalltime OWNER TO sokker_web;

--
-- Name: arcades_rankalltime_id_seq; Type: SEQUENCE; Schema: public; Owner: sokker_web
--

ALTER TABLE public.arcades_rankalltime ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.arcades_rankalltime_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: arcades_rankgroups; Type: TABLE; Schema: public; Owner: sokker_web
--

CREATE TABLE public.arcades_rankgroups (
    id integer NOT NULL,
    games integer,
    g_id integer,
    wins integer,
    loose integer,
    gdif integer,
    points integer,
    gscored integer,
    grecieved integer,
    draw integer,
    qualified character varying(50) NOT NULL,
    c_id_id integer NOT NULL,
    t_id_id integer NOT NULL
);


ALTER TABLE public.arcades_rankgroups OWNER TO sokker_web;

--
-- Name: arcades_rankgroups_id_seq; Type: SEQUENCE; Schema: public; Owner: sokker_web
--

ALTER TABLE public.arcades_rankgroups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.arcades_rankgroups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: arcades_winners; Type: TABLE; Schema: public; Owner: sokker_web
--

CREATE TABLE public.arcades_winners (
    id integer NOT NULL,
    "position" integer,
    cup_id_id integer NOT NULL,
    team_id_id integer NOT NULL
);


ALTER TABLE public.arcades_winners OWNER TO sokker_web;

--
-- Name: arcades_winners_id_seq; Type: SEQUENCE; Schema: public; Owner: sokker_web
--

ALTER TABLE public.arcades_winners ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.arcades_winners_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: sokker_web
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO sokker_web;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: sokker_web
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: sokker_web
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO sokker_web;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: sokker_web
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: sokker_web
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO sokker_web;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: sokker_web
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: sokker_web
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO sokker_web;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: sokker_web
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO sokker_web;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: sokker_web
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: sokker_web
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: sokker_web
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO sokker_web;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: sokker_web
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cache_table; Type: TABLE; Schema: public; Owner: sokker_web
--

CREATE TABLE public.cache_table (
    cache_key character varying(255) NOT NULL,
    value text NOT NULL,
    expires timestamp with time zone NOT NULL
);


ALTER TABLE public.cache_table OWNER TO sokker_web;

--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: sokker_web
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO sokker_web;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: sokker_web
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: sokker_web
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO sokker_web;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: sokker_web
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: sokker_web
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO sokker_web;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: sokker_web
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: sokker_web
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO sokker_web;

--
-- Name: euro_cup; Type: TABLE; Schema: public; Owner: sokker_web
--

CREATE TABLE public.euro_cup (
    id integer NOT NULL,
    c_name character varying(255) NOT NULL,
    c_edition integer,
    c_teams integer,
    c_groups integer,
    c_g_winners integer,
    c_games_groups integer,
    c_games integer,
    c_status character varying(50) NOT NULL,
    c_draw_status character varying(50) NOT NULL,
    c_draw_date timestamp with time zone,
    c_notes text,
    c_active boolean NOT NULL,
    header_image character varying(100),
    forum_link character varying(255),
    c_flow integer
);


ALTER TABLE public.euro_cup OWNER TO sokker_web;

--
-- Name: euro_cup_c_id_seq; Type: SEQUENCE; Schema: public; Owner: sokker_web
--

ALTER TABLE public.euro_cup ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.euro_cup_c_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: euro_cupdraw; Type: TABLE; Schema: public; Owner: sokker_web
--

CREATE TABLE public.euro_cupdraw (
    id integer NOT NULL,
    g_id integer NOT NULL,
    c_id_id integer NOT NULL,
    t_id_id integer NOT NULL
);


ALTER TABLE public.euro_cupdraw OWNER TO sokker_web;

--
-- Name: euro_cupdraw_id_seq; Type: SEQUENCE; Schema: public; Owner: sokker_web
--

ALTER TABLE public.euro_cupdraw ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.euro_cupdraw_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: euro_cupteams; Type: TABLE; Schema: public; Owner: sokker_web
--

CREATE TABLE public.euro_cupteams (
    id integer NOT NULL,
    g_id integer NOT NULL,
    c_id_id integer NOT NULL,
    t_id_id integer NOT NULL
);


ALTER TABLE public.euro_cupteams OWNER TO sokker_web;

--
-- Name: euro_cupteams_id_seq; Type: SEQUENCE; Schema: public; Owner: sokker_web
--

ALTER TABLE public.euro_cupteams ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.euro_cupteams_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: euro_game; Type: TABLE; Schema: public; Owner: sokker_web
--

CREATE TABLE public.euro_game (
    id integer NOT NULL,
    g_status character varying(50) NOT NULL,
    group_id character varying NOT NULL,
    goals_home integer,
    goals_away integer,
    cup_round character varying(50) NOT NULL,
    "matchID" character varying(255) NOT NULL,
    playoff_position character varying(50),
    c_id_id integer NOT NULL,
    t_id_h_id integer NOT NULL,
    t_id_v_id integer NOT NULL
);


ALTER TABLE public.euro_game OWNER TO sokker_web;

--
-- Name: euro_game_id_seq; Type: SEQUENCE; Schema: public; Owner: sokker_web
--

ALTER TABLE public.euro_game ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.euro_game_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: euro_medals; Type: TABLE; Schema: public; Owner: sokker_web
--

CREATE TABLE public.euro_medals (
    id integer NOT NULL,
    position_1 integer,
    position_2 integer,
    position_3 integer,
    position_4 integer,
    t_id_id integer NOT NULL
);


ALTER TABLE public.euro_medals OWNER TO sokker_web;

--
-- Name: euro_medals_id_seq; Type: SEQUENCE; Schema: public; Owner: sokker_web
--

ALTER TABLE public.euro_medals ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.euro_medals_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: euro_ntteam; Type: TABLE; Schema: public; Owner: sokker_web
--

CREATE TABLE public.euro_ntteam (
    id integer NOT NULL,
    t_nation character varying(255) NOT NULL,
    t_name character varying(255) NOT NULL,
    t_manager character varying(255),
    t_s_ranking integer,
    t_sokker_id character varying(255) NOT NULL,
    t_email character varying(254),
    t_arena character varying(255) NOT NULL
);


ALTER TABLE public.euro_ntteam OWNER TO sokker_web;

--
-- Name: euro_ntteam_id_seq; Type: SEQUENCE; Schema: public; Owner: sokker_web
--

ALTER TABLE public.euro_ntteam ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.euro_ntteam_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: euro_rankalltime; Type: TABLE; Schema: public; Owner: sokker_web
--

CREATE TABLE public.euro_rankalltime (
    id integer NOT NULL,
    games integer,
    wins integer,
    loose integer,
    gdif integer,
    points integer,
    gscored integer,
    grecieved integer,
    draw integer,
    c_flow integer,
    t_id_id integer NOT NULL
);


ALTER TABLE public.euro_rankalltime OWNER TO sokker_web;

--
-- Name: euro_rankalltime_id_seq; Type: SEQUENCE; Schema: public; Owner: sokker_web
--

ALTER TABLE public.euro_rankalltime ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.euro_rankalltime_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: euro_rankgroups; Type: TABLE; Schema: public; Owner: sokker_web
--

CREATE TABLE public.euro_rankgroups (
    id integer NOT NULL,
    games integer,
    g_id integer,
    wins integer,
    loose integer,
    gdif integer,
    points integer,
    gscored integer,
    grecieved integer,
    draw integer,
    qualified character varying(50) NOT NULL,
    c_id_id integer NOT NULL,
    t_id_id integer NOT NULL
);


ALTER TABLE public.euro_rankgroups OWNER TO sokker_web;

--
-- Name: euro_rankgroups_id_seq; Type: SEQUENCE; Schema: public; Owner: sokker_web
--

ALTER TABLE public.euro_rankgroups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.euro_rankgroups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: euro_winners; Type: TABLE; Schema: public; Owner: sokker_web
--

CREATE TABLE public.euro_winners (
    id integer NOT NULL,
    "position" integer,
    cup_id_id integer NOT NULL,
    team_id_id integer NOT NULL
);


ALTER TABLE public.euro_winners OWNER TO sokker_web;

--
-- Name: euro_winners_id_seq; Type: SEQUENCE; Schema: public; Owner: sokker_web
--

ALTER TABLE public.euro_winners ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.euro_winners_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ntdb_archiveplayer; Type: TABLE; Schema: public; Owner: sokker_web
--

CREATE TABLE public.ntdb_archiveplayer (
    id bigint NOT NULL,
    name character varying(255),
    surname character varying(255),
    countryid integer,
    age integer,
    teamid_id integer,
    youthteamid_id integer,
    value integer,
    wage integer,
    cards integer,
    goals integer,
    assists integer,
    matches integer,
    ntcards integer,
    ntgoals integer,
    ntassists integer,
    ntmatches integer,
    injurydays integer,
    "national" integer,
    skillform integer,
    skillexperience integer,
    skillteamwork integer,
    skilldiscipline integer,
    transferlist integer,
    skillstamina integer,
    skillpace integer,
    skilltechnique integer,
    skillpassing integer,
    skillkeeper integer,
    skilldefending integer,
    skillplaymaking integer,
    skillscoring integer,
    "position" character varying(3),
    date character varying(20),
    modified timestamp with time zone,
    height integer,
    sokker_id integer,
    weight integer,
    daily_update timestamp with time zone
);


ALTER TABLE public.ntdb_archiveplayer OWNER TO sokker_web;

--
-- Name: ntdb_archiveplayer_id_seq; Type: SEQUENCE; Schema: public; Owner: sokker_web
--

ALTER TABLE public.ntdb_archiveplayer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ntdb_archiveplayer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ntdb_player; Type: TABLE; Schema: public; Owner: sokker_web
--

CREATE TABLE public.ntdb_player (
    id bigint NOT NULL,
    name character varying(255),
    surname character varying(255),
    countryid integer,
    age integer,
    teamid_id integer,
    youthteamid_id integer,
    value integer,
    wage integer,
    cards integer,
    goals integer,
    assists integer,
    matches integer,
    ntcards integer,
    ntgoals integer,
    ntassists integer,
    ntmatches integer,
    injurydays integer,
    "national" integer,
    skillform integer,
    skillexperience integer,
    skillteamwork integer,
    skilldiscipline integer,
    transferlist integer,
    skillstamina integer,
    skillpace integer,
    skilltechnique integer,
    skillpassing integer,
    skillkeeper integer,
    skilldefending integer,
    skillplaymaking integer,
    skillscoring integer,
    "position" character varying(3),
    date character varying(20),
    modified timestamp with time zone,
    height integer,
    note text,
    sokker_id integer,
    weight integer,
    daily_update timestamp with time zone
);


ALTER TABLE public.ntdb_player OWNER TO sokker_web;

--
-- Name: ntdb_player_id_seq; Type: SEQUENCE; Schema: public; Owner: sokker_web
--

ALTER TABLE public.ntdb_player ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ntdb_player_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sokker_base_country; Type: TABLE; Schema: public; Owner: sokker_web
--

CREATE TABLE public.sokker_base_country (
    name character varying(100) NOT NULL,
    currency_name character varying(100),
    currency_rate numeric(10,2),
    code integer NOT NULL,
    id integer NOT NULL,
    active boolean NOT NULL
);


ALTER TABLE public.sokker_base_country OWNER TO sokker_web;

--
-- Name: sokker_base_pointsrequirementscountry; Type: TABLE; Schema: public; Owner: sokker_web
--

CREATE TABLE public.sokker_base_pointsrequirementscountry (
    id bigint NOT NULL,
    age integer,
    gk_points numeric(10,2),
    def_points numeric(10,2),
    mid_points numeric(10,2),
    att_points numeric(10,2),
    country_id integer
);


ALTER TABLE public.sokker_base_pointsrequirementscountry OWNER TO sokker_web;

--
-- Name: sokker_base_pointsrequirementscountry_id_seq; Type: SEQUENCE; Schema: public; Owner: sokker_web
--

ALTER TABLE public.sokker_base_pointsrequirementscountry ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sokker_base_pointsrequirementscountry_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sokker_base_team; Type: TABLE; Schema: public; Owner: sokker_web
--

CREATE TABLE public.sokker_base_team (
    id integer NOT NULL,
    name character varying(250) NOT NULL,
    country_id integer,
    daily_update timestamp with time zone
);


ALTER TABLE public.sokker_base_team OWNER TO sokker_web;

--
-- Name: sokker_base_usercountry; Type: TABLE; Schema: public; Owner: sokker_web
--

CREATE TABLE public.sokker_base_usercountry (
    id bigint NOT NULL,
    country_id integer,
    user_id integer NOT NULL,
    is_default boolean NOT NULL
);


ALTER TABLE public.sokker_base_usercountry OWNER TO sokker_web;

--
-- Name: sokker_base_usercountry_id_seq; Type: SEQUENCE; Schema: public; Owner: sokker_web
--

ALTER TABLE public.sokker_base_usercountry ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sokker_base_usercountry_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: arcades_cup arcades_cup_pkey; Type: CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.arcades_cup
    ADD CONSTRAINT arcades_cup_pkey PRIMARY KEY (id);


--
-- Name: arcades_cupcategory arcades_cupcategory_pkey; Type: CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.arcades_cupcategory
    ADD CONSTRAINT arcades_cupcategory_pkey PRIMARY KEY (id);


--
-- Name: arcades_cupdraw arcades_cupdraw_pkey; Type: CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.arcades_cupdraw
    ADD CONSTRAINT arcades_cupdraw_pkey PRIMARY KEY (id);


--
-- Name: arcades_cupteams arcades_cupteams_pkey; Type: CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.arcades_cupteams
    ADD CONSTRAINT arcades_cupteams_pkey PRIMARY KEY (id);


--
-- Name: arcades_game arcades_game_pkey; Type: CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.arcades_game
    ADD CONSTRAINT arcades_game_pkey PRIMARY KEY (id);


--
-- Name: arcades_medals arcades_medals_pkey; Type: CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.arcades_medals
    ADD CONSTRAINT arcades_medals_pkey PRIMARY KEY (id);


--
-- Name: arcades_rankalltime arcades_rankalltime_pkey; Type: CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.arcades_rankalltime
    ADD CONSTRAINT arcades_rankalltime_pkey PRIMARY KEY (id);


--
-- Name: arcades_rankgroups arcades_rankgroups_pkey; Type: CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.arcades_rankgroups
    ADD CONSTRAINT arcades_rankgroups_pkey PRIMARY KEY (id);


--
-- Name: arcades_winners arcades_winners_pkey; Type: CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.arcades_winners
    ADD CONSTRAINT arcades_winners_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: cache_table cache_table_pkey; Type: CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.cache_table
    ADD CONSTRAINT cache_table_pkey PRIMARY KEY (cache_key);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: euro_cup euro_cup_pkey; Type: CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.euro_cup
    ADD CONSTRAINT euro_cup_pkey PRIMARY KEY (id);


--
-- Name: euro_cupdraw euro_cupdraw_pkey; Type: CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.euro_cupdraw
    ADD CONSTRAINT euro_cupdraw_pkey PRIMARY KEY (id);


--
-- Name: euro_cupteams euro_cupteams_pkey; Type: CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.euro_cupteams
    ADD CONSTRAINT euro_cupteams_pkey PRIMARY KEY (id);


--
-- Name: euro_game euro_game_pkey; Type: CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.euro_game
    ADD CONSTRAINT euro_game_pkey PRIMARY KEY (id);


--
-- Name: euro_medals euro_medals_pkey; Type: CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.euro_medals
    ADD CONSTRAINT euro_medals_pkey PRIMARY KEY (id);


--
-- Name: euro_ntteam euro_ntteam_pkey; Type: CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.euro_ntteam
    ADD CONSTRAINT euro_ntteam_pkey PRIMARY KEY (id);


--
-- Name: euro_rankalltime euro_rankalltime_pkey; Type: CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.euro_rankalltime
    ADD CONSTRAINT euro_rankalltime_pkey PRIMARY KEY (id);


--
-- Name: euro_rankgroups euro_rankgroups_pkey; Type: CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.euro_rankgroups
    ADD CONSTRAINT euro_rankgroups_pkey PRIMARY KEY (id);


--
-- Name: euro_winners euro_winners_pkey; Type: CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.euro_winners
    ADD CONSTRAINT euro_winners_pkey PRIMARY KEY (id);


--
-- Name: ntdb_archiveplayer ntdb_archiveplayer_id_07c0452b_pk; Type: CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.ntdb_archiveplayer
    ADD CONSTRAINT ntdb_archiveplayer_id_07c0452b_pk PRIMARY KEY (id);


--
-- Name: ntdb_player ntdb_player_id_9cfd92f3_pk; Type: CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.ntdb_player
    ADD CONSTRAINT ntdb_player_id_9cfd92f3_pk PRIMARY KEY (id);


--
-- Name: sokker_base_country sokker_base_country_code_89380159_uniq; Type: CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.sokker_base_country
    ADD CONSTRAINT sokker_base_country_code_89380159_uniq UNIQUE (code);


--
-- Name: sokker_base_country sokker_base_country_pkey; Type: CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.sokker_base_country
    ADD CONSTRAINT sokker_base_country_pkey PRIMARY KEY (id);


--
-- Name: sokker_base_pointsrequirementscountry sokker_base_pointsrequirementscountry_pkey; Type: CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.sokker_base_pointsrequirementscountry
    ADD CONSTRAINT sokker_base_pointsrequirementscountry_pkey PRIMARY KEY (id);


--
-- Name: sokker_base_team sokker_base_team_pkey; Type: CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.sokker_base_team
    ADD CONSTRAINT sokker_base_team_pkey PRIMARY KEY (id);


--
-- Name: sokker_base_usercountry sokker_base_usercountry_pkey; Type: CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.sokker_base_usercountry
    ADD CONSTRAINT sokker_base_usercountry_pkey PRIMARY KEY (id);


--
-- Name: sokker_base_usercountry sokker_base_usercountry_user_id_country_id_da5e926a_uniq; Type: CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.sokker_base_usercountry
    ADD CONSTRAINT sokker_base_usercountry_user_id_country_id_da5e926a_uniq UNIQUE (user_id, country_id);


--
-- Name: arcades_cup_category_id_9837f90e; Type: INDEX; Schema: public; Owner: sokker_web
--

CREATE INDEX arcades_cup_category_id_9837f90e ON public.arcades_cup USING btree (category_id);


--
-- Name: arcades_cupdraw_c_id_id_9773304c; Type: INDEX; Schema: public; Owner: sokker_web
--

CREATE INDEX arcades_cupdraw_c_id_id_9773304c ON public.arcades_cupdraw USING btree (c_id_id);


--
-- Name: arcades_cupdraw_t_id_id_5c9129ec; Type: INDEX; Schema: public; Owner: sokker_web
--

CREATE INDEX arcades_cupdraw_t_id_id_5c9129ec ON public.arcades_cupdraw USING btree (t_id_id);


--
-- Name: arcades_cupteams_c_id_id_af3da72b; Type: INDEX; Schema: public; Owner: sokker_web
--

CREATE INDEX arcades_cupteams_c_id_id_af3da72b ON public.arcades_cupteams USING btree (c_id_id);


--
-- Name: arcades_cupteams_t_id_id_92f443e9; Type: INDEX; Schema: public; Owner: sokker_web
--

CREATE INDEX arcades_cupteams_t_id_id_92f443e9 ON public.arcades_cupteams USING btree (t_id_id);


--
-- Name: arcades_game_c_id_id_61fef62d; Type: INDEX; Schema: public; Owner: sokker_web
--

CREATE INDEX arcades_game_c_id_id_61fef62d ON public.arcades_game USING btree (c_id_id);


--
-- Name: arcades_game_t_id_h_id_9ca7663f; Type: INDEX; Schema: public; Owner: sokker_web
--

CREATE INDEX arcades_game_t_id_h_id_9ca7663f ON public.arcades_game USING btree (t_id_h_id);


--
-- Name: arcades_game_t_id_v_id_724c6e6e; Type: INDEX; Schema: public; Owner: sokker_web
--

CREATE INDEX arcades_game_t_id_v_id_724c6e6e ON public.arcades_game USING btree (t_id_v_id);


--
-- Name: arcades_medals_t_id_id_4a0484ab; Type: INDEX; Schema: public; Owner: sokker_web
--

CREATE INDEX arcades_medals_t_id_id_4a0484ab ON public.arcades_medals USING btree (t_id_id);


--
-- Name: arcades_rankalltime_t_id_id_21caaef9; Type: INDEX; Schema: public; Owner: sokker_web
--

CREATE INDEX arcades_rankalltime_t_id_id_21caaef9 ON public.arcades_rankalltime USING btree (t_id_id);


--
-- Name: arcades_rankgroups_c_id_id_2aa5ecbc; Type: INDEX; Schema: public; Owner: sokker_web
--

CREATE INDEX arcades_rankgroups_c_id_id_2aa5ecbc ON public.arcades_rankgroups USING btree (c_id_id);


--
-- Name: arcades_rankgroups_t_id_id_2abe1396; Type: INDEX; Schema: public; Owner: sokker_web
--

CREATE INDEX arcades_rankgroups_t_id_id_2abe1396 ON public.arcades_rankgroups USING btree (t_id_id);


--
-- Name: arcades_winners_cup_id_id_763bc9a2; Type: INDEX; Schema: public; Owner: sokker_web
--

CREATE INDEX arcades_winners_cup_id_id_763bc9a2 ON public.arcades_winners USING btree (cup_id_id);


--
-- Name: arcades_winners_team_id_id_7667291a; Type: INDEX; Schema: public; Owner: sokker_web
--

CREATE INDEX arcades_winners_team_id_id_7667291a ON public.arcades_winners USING btree (team_id_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: sokker_web
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: sokker_web
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: sokker_web
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: sokker_web
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: sokker_web
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: sokker_web
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: sokker_web
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: sokker_web
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: sokker_web
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: cache_table_expires; Type: INDEX; Schema: public; Owner: sokker_web
--

CREATE INDEX cache_table_expires ON public.cache_table USING btree (expires);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: sokker_web
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: sokker_web
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: sokker_web
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: sokker_web
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: euro_cupdraw_c_id_id_2e83416c; Type: INDEX; Schema: public; Owner: sokker_web
--

CREATE INDEX euro_cupdraw_c_id_id_2e83416c ON public.euro_cupdraw USING btree (c_id_id);


--
-- Name: euro_cupdraw_t_id_id_95c2f990; Type: INDEX; Schema: public; Owner: sokker_web
--

CREATE INDEX euro_cupdraw_t_id_id_95c2f990 ON public.euro_cupdraw USING btree (t_id_id);


--
-- Name: euro_cupteams_c_id_id_06613418; Type: INDEX; Schema: public; Owner: sokker_web
--

CREATE INDEX euro_cupteams_c_id_id_06613418 ON public.euro_cupteams USING btree (c_id_id);


--
-- Name: euro_cupteams_t_id_id_a2b5590b; Type: INDEX; Schema: public; Owner: sokker_web
--

CREATE INDEX euro_cupteams_t_id_id_a2b5590b ON public.euro_cupteams USING btree (t_id_id);


--
-- Name: euro_game_c_id_id_5acbeedd; Type: INDEX; Schema: public; Owner: sokker_web
--

CREATE INDEX euro_game_c_id_id_5acbeedd ON public.euro_game USING btree (c_id_id);


--
-- Name: euro_game_t_id_h_id_e38e6ff9; Type: INDEX; Schema: public; Owner: sokker_web
--

CREATE INDEX euro_game_t_id_h_id_e38e6ff9 ON public.euro_game USING btree (t_id_h_id);


--
-- Name: euro_game_t_id_v_id_6160d849; Type: INDEX; Schema: public; Owner: sokker_web
--

CREATE INDEX euro_game_t_id_v_id_6160d849 ON public.euro_game USING btree (t_id_v_id);


--
-- Name: euro_medals_t_id_id_a561807f; Type: INDEX; Schema: public; Owner: sokker_web
--

CREATE INDEX euro_medals_t_id_id_a561807f ON public.euro_medals USING btree (t_id_id);


--
-- Name: euro_rankalltime_t_id_id_0e142f17; Type: INDEX; Schema: public; Owner: sokker_web
--

CREATE INDEX euro_rankalltime_t_id_id_0e142f17 ON public.euro_rankalltime USING btree (t_id_id);


--
-- Name: euro_rankgroups_c_id_id_37460bfc; Type: INDEX; Schema: public; Owner: sokker_web
--

CREATE INDEX euro_rankgroups_c_id_id_37460bfc ON public.euro_rankgroups USING btree (c_id_id);


--
-- Name: euro_rankgroups_t_id_h_id_3ddaa68c; Type: INDEX; Schema: public; Owner: sokker_web
--

CREATE INDEX euro_rankgroups_t_id_h_id_3ddaa68c ON public.euro_rankgroups USING btree (t_id_id);


--
-- Name: euro_winners_cup_id_id_f832ee6e; Type: INDEX; Schema: public; Owner: sokker_web
--

CREATE INDEX euro_winners_cup_id_id_f832ee6e ON public.euro_winners USING btree (cup_id_id);


--
-- Name: euro_winners_team_id_id_eeb6d6b2; Type: INDEX; Schema: public; Owner: sokker_web
--

CREATE INDEX euro_winners_team_id_id_eeb6d6b2 ON public.euro_winners USING btree (team_id_id);


--
-- Name: ntdb_archiveplayer_teamid_id_6aac4430; Type: INDEX; Schema: public; Owner: sokker_web
--

CREATE INDEX ntdb_archiveplayer_teamid_id_6aac4430 ON public.ntdb_archiveplayer USING btree (teamid_id);


--
-- Name: ntdb_archiveplayer_youthteamid_id_9c905e3c; Type: INDEX; Schema: public; Owner: sokker_web
--

CREATE INDEX ntdb_archiveplayer_youthteamid_id_9c905e3c ON public.ntdb_archiveplayer USING btree (youthteamid_id);


--
-- Name: ntdb_player_teamid_id_17826fad; Type: INDEX; Schema: public; Owner: sokker_web
--

CREATE INDEX ntdb_player_teamid_id_17826fad ON public.ntdb_player USING btree (teamid_id);


--
-- Name: ntdb_player_youthteamid_id_538c7831; Type: INDEX; Schema: public; Owner: sokker_web
--

CREATE INDEX ntdb_player_youthteamid_id_538c7831 ON public.ntdb_player USING btree (youthteamid_id);


--
-- Name: sokker_base_pointsrequirementscountry_country_id_f636b721; Type: INDEX; Schema: public; Owner: sokker_web
--

CREATE INDEX sokker_base_pointsrequirementscountry_country_id_f636b721 ON public.sokker_base_pointsrequirementscountry USING btree (country_id);


--
-- Name: sokker_base_team_country_id_be61a92d; Type: INDEX; Schema: public; Owner: sokker_web
--

CREATE INDEX sokker_base_team_country_id_be61a92d ON public.sokker_base_team USING btree (country_id);


--
-- Name: sokker_base_usercountry_country_id_fe46292f; Type: INDEX; Schema: public; Owner: sokker_web
--

CREATE INDEX sokker_base_usercountry_country_id_fe46292f ON public.sokker_base_usercountry USING btree (country_id);


--
-- Name: sokker_base_usercountry_user_id_5c958609; Type: INDEX; Schema: public; Owner: sokker_web
--

CREATE INDEX sokker_base_usercountry_user_id_5c958609 ON public.sokker_base_usercountry USING btree (user_id);


--
-- Name: arcades_cup arcades_cup_category_id_9837f90e_fk_arcades_cupcategory_id; Type: FK CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.arcades_cup
    ADD CONSTRAINT arcades_cup_category_id_9837f90e_fk_arcades_cupcategory_id FOREIGN KEY (category_id) REFERENCES public.arcades_cupcategory(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: arcades_cupdraw arcades_cupdraw_c_id_id_9773304c_fk_arcades_cup_id; Type: FK CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.arcades_cupdraw
    ADD CONSTRAINT arcades_cupdraw_c_id_id_9773304c_fk_arcades_cup_id FOREIGN KEY (c_id_id) REFERENCES public.arcades_cup(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: arcades_cupdraw arcades_cupdraw_t_id_id_5c9129ec_fk_sokker_base_team_id; Type: FK CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.arcades_cupdraw
    ADD CONSTRAINT arcades_cupdraw_t_id_id_5c9129ec_fk_sokker_base_team_id FOREIGN KEY (t_id_id) REFERENCES public.sokker_base_team(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: arcades_cupteams arcades_cupteams_c_id_id_af3da72b_fk_arcades_cup_id; Type: FK CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.arcades_cupteams
    ADD CONSTRAINT arcades_cupteams_c_id_id_af3da72b_fk_arcades_cup_id FOREIGN KEY (c_id_id) REFERENCES public.arcades_cup(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: arcades_cupteams arcades_cupteams_t_id_id_92f443e9_fk_sokker_base_team_id; Type: FK CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.arcades_cupteams
    ADD CONSTRAINT arcades_cupteams_t_id_id_92f443e9_fk_sokker_base_team_id FOREIGN KEY (t_id_id) REFERENCES public.sokker_base_team(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: arcades_game arcades_game_c_id_id_61fef62d_fk_arcades_cup_id; Type: FK CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.arcades_game
    ADD CONSTRAINT arcades_game_c_id_id_61fef62d_fk_arcades_cup_id FOREIGN KEY (c_id_id) REFERENCES public.arcades_cup(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: arcades_game arcades_game_t_id_h_id_9ca7663f_fk_sokker_base_team_id; Type: FK CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.arcades_game
    ADD CONSTRAINT arcades_game_t_id_h_id_9ca7663f_fk_sokker_base_team_id FOREIGN KEY (t_id_h_id) REFERENCES public.sokker_base_team(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: arcades_game arcades_game_t_id_v_id_724c6e6e_fk_sokker_base_team_id; Type: FK CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.arcades_game
    ADD CONSTRAINT arcades_game_t_id_v_id_724c6e6e_fk_sokker_base_team_id FOREIGN KEY (t_id_v_id) REFERENCES public.sokker_base_team(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: arcades_medals arcades_medals_t_id_id_4a0484ab_fk_sokker_base_team_id; Type: FK CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.arcades_medals
    ADD CONSTRAINT arcades_medals_t_id_id_4a0484ab_fk_sokker_base_team_id FOREIGN KEY (t_id_id) REFERENCES public.sokker_base_team(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: arcades_rankalltime arcades_rankalltime_t_id_id_21caaef9_fk_sokker_base_team_id; Type: FK CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.arcades_rankalltime
    ADD CONSTRAINT arcades_rankalltime_t_id_id_21caaef9_fk_sokker_base_team_id FOREIGN KEY (t_id_id) REFERENCES public.sokker_base_team(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: arcades_rankgroups arcades_rankgroups_c_id_id_2aa5ecbc_fk_arcades_cup_id; Type: FK CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.arcades_rankgroups
    ADD CONSTRAINT arcades_rankgroups_c_id_id_2aa5ecbc_fk_arcades_cup_id FOREIGN KEY (c_id_id) REFERENCES public.arcades_cup(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: arcades_rankgroups arcades_rankgroups_t_id_id_2abe1396_fk_sokker_base_team_id; Type: FK CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.arcades_rankgroups
    ADD CONSTRAINT arcades_rankgroups_t_id_id_2abe1396_fk_sokker_base_team_id FOREIGN KEY (t_id_id) REFERENCES public.sokker_base_team(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: arcades_winners arcades_winners_cup_id_id_763bc9a2_fk_arcades_cup_id; Type: FK CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.arcades_winners
    ADD CONSTRAINT arcades_winners_cup_id_id_763bc9a2_fk_arcades_cup_id FOREIGN KEY (cup_id_id) REFERENCES public.arcades_cup(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: arcades_winners arcades_winners_team_id_id_7667291a_fk_sokker_base_team_id; Type: FK CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.arcades_winners
    ADD CONSTRAINT arcades_winners_team_id_id_7667291a_fk_sokker_base_team_id FOREIGN KEY (team_id_id) REFERENCES public.sokker_base_team(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: euro_cupdraw euro_cupdraw_c_id_id_2e83416c_fk_euro_cup_id; Type: FK CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.euro_cupdraw
    ADD CONSTRAINT euro_cupdraw_c_id_id_2e83416c_fk_euro_cup_id FOREIGN KEY (c_id_id) REFERENCES public.euro_cup(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: euro_cupdraw euro_cupdraw_t_id_id_95c2f990_fk_euro_ntteam_id; Type: FK CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.euro_cupdraw
    ADD CONSTRAINT euro_cupdraw_t_id_id_95c2f990_fk_euro_ntteam_id FOREIGN KEY (t_id_id) REFERENCES public.euro_ntteam(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: euro_cupteams euro_cupteams_c_id_id_06613418_fk_euro_cup_id; Type: FK CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.euro_cupteams
    ADD CONSTRAINT euro_cupteams_c_id_id_06613418_fk_euro_cup_id FOREIGN KEY (c_id_id) REFERENCES public.euro_cup(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: euro_cupteams euro_cupteams_t_id_id_a2b5590b_fk_euro_ntteam_id; Type: FK CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.euro_cupteams
    ADD CONSTRAINT euro_cupteams_t_id_id_a2b5590b_fk_euro_ntteam_id FOREIGN KEY (t_id_id) REFERENCES public.euro_ntteam(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: euro_game euro_game_c_id_id_5acbeedd_fk_euro_cup_id; Type: FK CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.euro_game
    ADD CONSTRAINT euro_game_c_id_id_5acbeedd_fk_euro_cup_id FOREIGN KEY (c_id_id) REFERENCES public.euro_cup(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: euro_game euro_game_t_id_h_id_e38e6ff9_fk_euro_ntteam_id; Type: FK CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.euro_game
    ADD CONSTRAINT euro_game_t_id_h_id_e38e6ff9_fk_euro_ntteam_id FOREIGN KEY (t_id_h_id) REFERENCES public.euro_ntteam(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: euro_game euro_game_t_id_v_id_6160d849_fk_euro_ntteam_id; Type: FK CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.euro_game
    ADD CONSTRAINT euro_game_t_id_v_id_6160d849_fk_euro_ntteam_id FOREIGN KEY (t_id_v_id) REFERENCES public.euro_ntteam(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: euro_medals euro_medals_t_id_id_a561807f_fk_euro_ntteam_id; Type: FK CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.euro_medals
    ADD CONSTRAINT euro_medals_t_id_id_a561807f_fk_euro_ntteam_id FOREIGN KEY (t_id_id) REFERENCES public.euro_ntteam(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: euro_rankalltime euro_rankalltime_t_id_id_0e142f17_fk_euro_ntteam_id; Type: FK CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.euro_rankalltime
    ADD CONSTRAINT euro_rankalltime_t_id_id_0e142f17_fk_euro_ntteam_id FOREIGN KEY (t_id_id) REFERENCES public.euro_ntteam(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: euro_rankgroups euro_rankgroups_c_id_id_37460bfc_fk_euro_cup_id; Type: FK CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.euro_rankgroups
    ADD CONSTRAINT euro_rankgroups_c_id_id_37460bfc_fk_euro_cup_id FOREIGN KEY (c_id_id) REFERENCES public.euro_cup(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: euro_rankgroups euro_rankgroups_t_id_id_4a3c0e79_fk_euro_ntteam_id; Type: FK CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.euro_rankgroups
    ADD CONSTRAINT euro_rankgroups_t_id_id_4a3c0e79_fk_euro_ntteam_id FOREIGN KEY (t_id_id) REFERENCES public.euro_ntteam(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: euro_winners euro_winners_cup_id_id_f832ee6e_fk_euro_cup_id; Type: FK CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.euro_winners
    ADD CONSTRAINT euro_winners_cup_id_id_f832ee6e_fk_euro_cup_id FOREIGN KEY (cup_id_id) REFERENCES public.euro_cup(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: euro_winners euro_winners_team_id_id_eeb6d6b2_fk_euro_ntteam_id; Type: FK CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.euro_winners
    ADD CONSTRAINT euro_winners_team_id_id_eeb6d6b2_fk_euro_ntteam_id FOREIGN KEY (team_id_id) REFERENCES public.euro_ntteam(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ntdb_archiveplayer ntdb_archiveplayer_teamid_id_6aac4430_fk_sokker_base_team_id; Type: FK CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.ntdb_archiveplayer
    ADD CONSTRAINT ntdb_archiveplayer_teamid_id_6aac4430_fk_sokker_base_team_id FOREIGN KEY (teamid_id) REFERENCES public.sokker_base_team(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ntdb_archiveplayer ntdb_archiveplayer_youthteamid_id_9c905e3c_fk_sokker_ba; Type: FK CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.ntdb_archiveplayer
    ADD CONSTRAINT ntdb_archiveplayer_youthteamid_id_9c905e3c_fk_sokker_ba FOREIGN KEY (youthteamid_id) REFERENCES public.sokker_base_team(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ntdb_player ntdb_player_teamid_id_17826fad_fk_sokker_base_team_id; Type: FK CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.ntdb_player
    ADD CONSTRAINT ntdb_player_teamid_id_17826fad_fk_sokker_base_team_id FOREIGN KEY (teamid_id) REFERENCES public.sokker_base_team(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ntdb_player ntdb_player_youthteamid_id_538c7831_fk_sokker_base_team_id; Type: FK CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.ntdb_player
    ADD CONSTRAINT ntdb_player_youthteamid_id_538c7831_fk_sokker_base_team_id FOREIGN KEY (youthteamid_id) REFERENCES public.sokker_base_team(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: sokker_base_pointsrequirementscountry sokker_base_pointsre_country_id_f636b721_fk_sokker_ba; Type: FK CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.sokker_base_pointsrequirementscountry
    ADD CONSTRAINT sokker_base_pointsre_country_id_f636b721_fk_sokker_ba FOREIGN KEY (country_id) REFERENCES public.sokker_base_country(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: sokker_base_team sokker_base_team_country_id_be61a92d_fk_sokker_ba; Type: FK CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.sokker_base_team
    ADD CONSTRAINT sokker_base_team_country_id_be61a92d_fk_sokker_ba FOREIGN KEY (country_id) REFERENCES public.sokker_base_country(code) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: sokker_base_usercountry sokker_base_usercoun_country_id_fe46292f_fk_sokker_ba; Type: FK CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.sokker_base_usercountry
    ADD CONSTRAINT sokker_base_usercoun_country_id_fe46292f_fk_sokker_ba FOREIGN KEY (country_id) REFERENCES public.sokker_base_country(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: sokker_base_usercountry sokker_base_usercountry_user_id_5c958609_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: sokker_web
--

ALTER TABLE ONLY public.sokker_base_usercountry
    ADD CONSTRAINT sokker_base_usercountry_user_id_5c958609_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: pg_database_owner
--

REVOKE USAGE ON SCHEMA public FROM PUBLIC;
GRANT ALL ON SCHEMA public TO PUBLIC;


--
-- PostgreSQL database dump complete
--

