# Generated by Django 4.2.11 on 2024-10-01 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sokker_base', '0014_alter_team_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='header_images/')),
                ('forum_link', models.CharField(blank=True, max_length=255, null=True)),
                ('c_name', models.CharField(max_length=255)),
                ('c_edition', models.IntegerField(blank=True, null=True)),
                ('c_flow', models.IntegerField(blank=True, default=1, null=True)),
                ('c_teams', models.IntegerField(blank=True, null=True)),
                ('c_groups', models.IntegerField(blank=True, null=True)),
                ('c_g_winners', models.IntegerField(blank=True, null=True)),
                ('c_games_groups', models.IntegerField(blank=True, null=True)),
                ('c_games', models.IntegerField(blank=True, null=True)),
                ('c_status', models.CharField(max_length=50)),
                ('c_draw_status', models.CharField(max_length=50)),
                ('c_draw_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('c_notes', models.TextField(blank=True, null=True)),
                ('c_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Winners',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('cup_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arcades.cup')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_winners', to='sokker_base.team')),
            ],
            options={
                'verbose_name_plural': 'Winners',
            },
        ),
        migrations.CreateModel(
            name='RankGroups',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('games', models.IntegerField(blank=True, null=True)),
                ('g_id', models.IntegerField(blank=True, null=True)),
                ('wins', models.IntegerField(blank=True, null=True)),
                ('loose', models.IntegerField(blank=True, null=True)),
                ('gdif', models.IntegerField(blank=True, null=True)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('gscored', models.IntegerField(blank=True, null=True)),
                ('grecieved', models.IntegerField(blank=True, null=True)),
                ('draw', models.IntegerField(blank=True, null=True)),
                ('qualified', models.CharField(max_length=50)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arcades.cup')),
                ('t_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_rank_arcades', to='sokker_base.team')),
            ],
            options={
                'verbose_name_plural': 'Rank Groups',
            },
        ),
        migrations.CreateModel(
            name='RankAllTime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('games', models.IntegerField(blank=True, null=True)),
                ('wins', models.IntegerField(blank=True, null=True)),
                ('loose', models.IntegerField(blank=True, null=True)),
                ('gdif', models.IntegerField(blank=True, null=True)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('gscored', models.IntegerField(blank=True, null=True)),
                ('grecieved', models.IntegerField(blank=True, null=True)),
                ('draw', models.IntegerField(blank=True, null=True)),
                ('c_flow', models.IntegerField(blank=True, default=1, null=True)),
                ('t_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_rank_all_time', to='sokker_base.team')),
            ],
        ),
        migrations.CreateModel(
            name='Medals',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('position_1', models.IntegerField(blank=True, null=True)),
                ('position_2', models.IntegerField(blank=True, null=True)),
                ('position_3', models.IntegerField(blank=True, null=True)),
                ('position_4', models.IntegerField(blank=True, null=True)),
                ('t_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_medal_arcades', to='sokker_base.team')),
            ],
            options={
                'verbose_name_plural': 'Medals',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('g_status', models.CharField(max_length=50)),
                ('group_id', models.CharField()),
                ('goals_home', models.IntegerField(blank=True, null=True)),
                ('goals_away', models.IntegerField(blank=True, null=True)),
                ('cup_round', models.CharField(max_length=50)),
                ('matchID', models.CharField(max_length=255)),
                ('playoff_position', models.CharField(blank=True, max_length=50, null=True)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arcades.cup')),
                ('t_id_h', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team_base', to='sokker_base.team')),
                ('t_id_v', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team_base', to='sokker_base.team')),
            ],
        ),
        migrations.CreateModel(
            name='CupTeams',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('g_id', models.IntegerField()),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arcades.cup')),
                ('t_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sokker_base.team')),
            ],
            options={
                'verbose_name_plural': 'Cup Teams',
            },
        ),
        migrations.CreateModel(
            name='CupDraw',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('g_id', models.IntegerField()),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arcades.cup')),
                ('t_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sokker_base.team')),
            ],
        ),
    ]
