# Generated by Django 4.2.11 on 2024-10-01 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sokker_base', '0014_alter_team_country'),
        ('arcades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='t_id_h',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_base', to='sokker_base.team'),
        ),
        migrations.AlterField(
            model_name='game',
            name='t_id_v',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_base', to='sokker_base.team'),
        ),
    ]
