# Generated by Django 4.2.11 on 2024-10-02 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sokker_base', '0014_alter_team_country'),
        ('arcades', '0002_alter_game_t_id_h_alter_game_t_id_v'),
    ]

    operations = [
        migrations.CreateModel(
            name='CupCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='t_id_h',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_base', to='sokker_base.team'),
        ),
        migrations.AlterField(
            model_name='game',
            name='t_id_v',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_base', to='sokker_base.team'),
        ),
        migrations.AddField(
            model_name='cup',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='arcades.cupcategory'),
        ),
    ]
