# Generated by Django 4.2.11 on 2024-12-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcades', '0004_cup_is_cl'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupteams',
            name='pot_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
