# Generated by Django 4.2.11 on 2025-01-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcades', '0005_cupteams_pot_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cup',
            name='c_start_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
