# Generated by Django 4.2.11 on 2025-01-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcades', '0006_cup_c_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupteams',
            name='rating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
