# Generated by Django 4.2.11 on 2025-01-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcades', '0007_cupteams_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupteams',
            name='cl_draw',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
