# Generated by Django 4.2.11 on 2025-01-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcades', '0008_cupteams_cl_draw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='g_status',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
