# Generated by Django 4.2.11 on 2025-04-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcades', '0010_cup_rating_limit_game_rating_away_game_rating_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cup',
            name='c_draw_status',
            field=models.CharField(blank=True, choices=[('ready', 'Ready'), ('done', 'Done'), ('signup', 'Signup')], default='', max_length=50, null=True),
        ),
    ]
