# Generated by Django 4.2.11 on 2025-04-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcades', '0011_alter_cup_c_draw_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cup',
            name='c_status',
            field=models.CharField(blank=True, choices=[('ready', 'Ready'), ('done', 'Done'), ('signup', 'Signup'), ('draw', 'Draw'), ('fixtures', 'Fixtures')], default='', max_length=50, null=True),
        ),
    ]
