# Generated by Django 4.2.11 on 2025-04-10 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcades', '0012_alter_cup_c_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupdraw',
            name='rating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
