# Generated by Django 4.2.11 on 2025-05-08 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sokker_base', '0018_leaguetable'),
        ('arcades', '0013_cupdraw_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sokker_base.country')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sokker_base.team')),
            ],
        ),
        migrations.CreateModel(
            name='CupGoalScorer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('goal', models.IntegerField(blank=True, null=True)),
                ('minute', models.IntegerField(blank=True, null=True)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arcades.cup')),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arcades.game')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arcades.player')),
                ('t_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sokker_base.team')),
            ],
        ),
    ]
