# Generated by Django 4.2.11 on 2025-05-09 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sokker_base', '0018_leaguetable'),
        ('arcades', '0014_player_cupgoalscorer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CupGameStats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('goal', models.IntegerField(blank=True, null=True)),
                ('assists', models.IntegerField(blank=True, null=True)),
                ('red_cards', models.IntegerField(blank=True, null=True)),
                ('yellow_cards', models.IntegerField(blank=True, null=True)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arcades.cup')),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arcades.game')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arcades.player')),
                ('t_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sokker_base.team')),
            ],
        ),
        migrations.DeleteModel(
            name='CupGoalScorer',
        ),
    ]
