# Generated by Django 4.2.11 on 2025-05-09 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arcades', '0015_cupgamestats_delete_cupgoalscorer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cupgamestats',
            old_name='t_id',
            new_name='team_id',
        ),
        migrations.RemoveField(
            model_name='cupgamestats',
            name='c_id',
        ),
    ]
