# Generated by Django 4.2.11 on 2025-05-09 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arcades', '0016_rename_t_id_cupgamestats_team_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cupgamestats',
            old_name='goal',
            new_name='goals',
        ),
    ]
