# Generated by Django 4.2.11 on 2025-05-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcades', '0020_cup_match_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cup',
            name='match_days',
            field=models.JSONField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=list, help_text='List of weekdays when matches are played (0=Monday, 6=Sunday)'),
        ),
    ]
