# Generated by Django 4.2.11 on 2025-05-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcades', '0021_alter_cup_match_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cup',
            name='match_days',
            field=models.JSONField(default=list, help_text='List of weekdays when matches are played (0=Monday, 6=Sunday)'),
        ),
    ]
