# Generated by Django 4.2.11 on 2025-05-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcades', '0022_alter_cup_match_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='cup',
            name='looser_playoffs',
            field=models.BooleanField(default=False, help_text='If the loosers in groups play separate playoffs'),
        ),
        migrations.AlterField(
            model_name='cup',
            name='c_edition',
            field=models.IntegerField(blank=True, help_text='Edition of the cup', null=True),
        ),
        migrations.AlterField(
            model_name='cup',
            name='c_flow',
            field=models.IntegerField(blank=True, default=1, help_text='Flow of the cup if few cups are splited in different flows', null=True),
        ),
        migrations.AlterField(
            model_name='cup',
            name='c_g_winners',
            field=models.IntegerField(blank=True, help_text='Total Number of teams proceeding to the next round', null=True),
        ),
        migrations.AlterField(
            model_name='cup',
            name='c_games',
            field=models.IntegerField(blank=True, help_text='Number of games in the playoffs', null=True),
        ),
        migrations.AlterField(
            model_name='cup',
            name='c_games_groups',
            field=models.IntegerField(blank=True, help_text='Number of games in group stage between teams', null=True),
        ),
        migrations.AlterField(
            model_name='cup',
            name='c_groups',
            field=models.IntegerField(blank=True, help_text='Number of groups in the cup', null=True),
        ),
        migrations.AlterField(
            model_name='cup',
            name='c_name',
            field=models.CharField(help_text='Name of the cup', max_length=255),
        ),
        migrations.AlterField(
            model_name='cup',
            name='c_start_date',
            field=models.DateTimeField(blank=True, default=None, help_text='Start date of the cup 1 round', null=True),
        ),
        migrations.AlterField(
            model_name='cup',
            name='c_teams',
            field=models.IntegerField(blank=True, help_text='Total number of teams in the cup', null=True),
        ),
        migrations.AlterField(
            model_name='cup',
            name='forum_link',
            field=models.CharField(blank=True, help_text='Forum link for the cup', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cup',
            name='header_image',
            field=models.ImageField(blank=True, help_text='Header image for the cup 1920x300px', null=True, upload_to='header_images/'),
        ),
        migrations.AlterField(
            model_name='cup',
            name='is_cl',
            field=models.BooleanField(default=False, help_text='If the cup is a CL format'),
        ),
        migrations.AlterField(
            model_name='cup',
            name='match_days',
            field=models.JSONField(default=list, help_text='List of weekdays when matches can be played (0=Monday, 6=Sunday)'),
        ),
        migrations.AlterField(
            model_name='cup',
            name='rating_limit',
            field=models.FloatField(blank=True, default=None, help_text='Rating limit for the cup', null=True),
        ),
    ]
