# Generated by Django 4.2.11 on 2025-05-18 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sokker_base', '0018_leaguetable'),
        ('arcades', '0023_cup_looser_playoffs_alter_cup_c_edition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cup',
            name='draw_playoffs',
            field=models.BooleanField(default=False, help_text='If the playoffs have draw'),
        ),
        migrations.CreateModel(
            name='PlayoffPots',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pot_id', models.IntegerField(blank=True, null=True)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arcades.cup')),
                ('t_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sokker_base.team')),
            ],
        ),
        migrations.CreateModel(
            name='PlayoffDraw',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pot_id', models.IntegerField(blank=True, null=True)),
                ('draw_id', models.IntegerField(blank=True, null=True)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arcades.cup')),
                ('t_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sokker_base.team')),
            ],
        ),
    ]
