# Generated by Django 4.2.11 on 2025-05-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcades', '0024_cup_draw_playoffs_playoffpots_playoffdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='playoffdraw',
            name='flow',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playoffpots',
            name='flow',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
