# Generated by Django 4.2.11 on 2025-05-20 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sokker_base', '0018_leaguetable'),
        ('arcades', '0025_playoffdraw_flow_playoffpots_flow'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_home', models.BooleanField(default=False)),
                ('timeOnHalf', models.IntegerField(blank=True, null=True)),
                ('timePossession', models.IntegerField(blank=True, null=True)),
                ('shots', models.IntegerField(blank=True, null=True)),
                ('fouls', models.IntegerField(blank=True, null=True)),
                ('yellowCards', models.IntegerField(blank=True, null=True)),
                ('redCards', models.IntegerField(blank=True, null=True)),
                ('offsides', models.IntegerField(blank=True, null=True)),
                ('effShoot', models.IntegerField(blank=True, null=True)),
                ('effPass', models.IntegerField(blank=True, null=True)),
                ('effTackle', models.IntegerField(blank=True, null=True)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arcades.game')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sokker_base.team')),
            ],
        ),
    ]
