# Generated by Django 4.2.11 on 2025-05-20 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arcades', '0026_gamedetails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cupgamestats',
            options={'verbose_name_plural': 'Cup Game Stats'},
        ),
        migrations.AlterModelOptions(
            name='gamedetails',
            options={'verbose_name_plural': 'Game Details'},
        ),
    ]
