# Generated by Django 4.2.11 on 2025-05-20 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arcades', '0027_alter_cupgamestats_options_alter_gamedetails_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playoffpots',
            options={'verbose_name_plural': 'Playoff Pots'},
        ),
    ]
